# Generated by Django 4.2.3 on 2023-07-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_iletisimmodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yorummodel",
            old_name="guncellenme_tarihi",
            new_name="duzenlenme_tarihi",
        ),
    ]
