from .iletisim import IletisimView
from .anasayfa import anasayfa
from .kategori import KategoriView
from .yazilarim import yazilarim
from .detay import DetayView
from .yazi_ekle import YaziEkleView
from .yazi_guncelle import YaziGuncelleView
from .yazi_sil import YaziSilView
from .yorum_sil import yorum_sil